/**
 * Fetches model pricing from OpenRouter and generates a static pricing table.
 * Run at build time: `npx tsx scripts/fetch-pricing.ts`
 *
 * Falls back to the last committed version if the fetch fails.
 */

import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(__dirname, '..', 'src', 'generated', 'pricing.ts');

const OPENROUTER_API = 'https://openrouter.ai/api/v1/models';

// Map OpenRouter model IDs to anymodel provider prefixes
const PROVIDER_MAP: Record<string, string> = {
  'openai': 'openai',
  'anthropic': 'anthropic',
  'google': 'google',
  'mistralai': 'mistral',
  'meta-llama': 'meta',
  'deepseek': 'deepseek',
  'x-ai': 'xai',
  'perplexity': 'perplexity',
  'qwen': 'qwen',
  'cohere': 'cohere',
};

interface OpenRouterModel {
  id: string;
  name: string;
  pricing: {
    prompt: string;
    completion: string;
    input_cache_read?: string;
    input_cache_write?: string;
    web_search?: string;
  };
  context_length: number;
}

interface PricingEntry {
  prompt: number;
  completion: number;
  cacheRead?: number;
  cacheWrite?: number;
}

async function fetchPricing(): Promise<Map<string, PricingEntry>> {
  console.log('Fetching pricing from OpenRouter...');
  const res = await fetch(OPENROUTER_API);
  if (!res.ok) {
    throw new Error(`OpenRouter API returned ${res.status}: ${res.statusText}`);
  }

  const data = await res.json() as { data: OpenRouterModel[] };
  const pricing = new Map<string, PricingEntry>();

  for (const model of data.data) {
    if (!model.pricing?.prompt || !model.pricing?.completion) continue;

    const prompt = parseFloat(model.pricing.prompt);
    const completion = parseFloat(model.pricing.completion);

    // Skip free/zero-cost models
    if (prompt === 0 && completion === 0) continue;

    const entry: PricingEntry = { prompt, completion };
    if (model.pricing.input_cache_read) {
      entry.cacheRead = parseFloat(model.pricing.input_cache_read);
    }
    if (model.pricing.input_cache_write) {
      entry.cacheWrite = parseFloat(model.pricing.input_cache_write);
    }

    // Store with OpenRouter ID (provider/model format)
    pricing.set(model.id, entry);
  }

  console.log(`Fetched pricing for ${pricing.size} models`);
  return pricing;
}

function generateSource(pricing: Map<string, PricingEntry>): string {
  const now = new Date().toISOString();
  const entries: string[] = [];

  for (const [id, entry] of pricing) {
    const parts = [`prompt: ${entry.prompt}, completion: ${entry.completion}`];
    if (entry.cacheRead !== undefined) parts.push(`cacheRead: ${entry.cacheRead}`);
    if (entry.cacheWrite !== undefined) parts.push(`cacheWrite: ${entry.cacheWrite}`);
    entries.push(`  '${id}': { ${parts.join(', ')} }`);
  }

  return `// Auto-generated by scripts/fetch-pricing.ts — DO NOT EDIT
// Source: OpenRouter /api/v1/models
// Generated: ${now}

export interface PricingEntry {
  /** Cost per token for input/prompt */
  prompt: number;
  /** Cost per token for output/completion */
  completion: number;
  /** Cost per token for cached input reads */
  cacheRead?: number;
  /** Cost per token for cached input writes */
  cacheWrite?: number;
}

/** Date this pricing data was fetched */
export const PRICING_AS_OF = '${now}';

/** Number of models with pricing data */
export const PRICING_MODEL_COUNT = ${pricing.size};

/**
 * Model pricing table keyed by OpenRouter model ID (provider/model format).
 * Costs are per-token in USD.
 */
export const MODEL_PRICING: Record<string, PricingEntry> = {
${entries.join(',\n')},
};

/**
 * Look up pricing for a model. Tries exact match first,
 * then falls back to prefix matching for versioned models.
 */
export function getModelPricing(modelId: string): PricingEntry | null {
  // Exact match
  if (MODEL_PRICING[modelId]) return MODEL_PRICING[modelId];

  // Try without anymodel provider prefix remapping
  // e.g. "openai/gpt-4o" is already the OpenRouter format

  // Prefix match: "openai/gpt-4o-2024-08-06" → "openai/gpt-4o"
  for (const [id, pricing] of Object.entries(MODEL_PRICING)) {
    if (modelId.startsWith(id) || id.startsWith(modelId)) {
      return pricing;
    }
  }

  return null;
}

/**
 * Calculate the cost for a request given token counts.
 */
export function calculateCost(
  modelId: string,
  promptTokens: number,
  completionTokens: number,
): number {
  const pricing = getModelPricing(modelId);
  if (!pricing) return 0;
  return (promptTokens * pricing.prompt) + (completionTokens * pricing.completion);
}
`;
}

async function main() {
  const generatedDir = join(__dirname, '..', 'src', 'generated');
  if (!existsSync(generatedDir)) {
    const { mkdirSync } = await import('node:fs');
    mkdirSync(generatedDir, { recursive: true });
  }

  try {
    const pricing = await fetchPricing();
    const source = generateSource(pricing);
    writeFileSync(OUTPUT_PATH, source);
    console.log(`Written to ${OUTPUT_PATH}`);
  } catch (err) {
    console.error('Failed to fetch pricing:', (err as Error).message);
    if (existsSync(OUTPUT_PATH)) {
      console.log('Using existing pricing data as fallback');
    } else {
      console.error('No fallback available — generating empty pricing table');
      const empty = generateSource(new Map());
      writeFileSync(OUTPUT_PATH, empty);
    }
    process.exit(0); // Don't fail the build
  }
}

main();
